map_type: costmap
obstacle_range: 5
raytrace_range: 6
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
footprint: [ [-23, -0.23], [-0.23, 0.23], [0.23, 0.23], [0.23, -0.23] ]
#robot_radius: ir_of_robot
robot_radius: 0.5 # distance a circular robot should be clear of the obstacle

inflation:
    inflation_radius: 3.0

transform_tolerance: 1.0

sensor:

    observation_sources: laser_scan_sensor #point_cloud_sensor

    # marking - add obstacle information to cost map
    # clearing - clear obstacle information to cost map
    laser_scan_sensor: {sensor_frame: sensor_laser, data_type: LaserScan, topic: /owr_rover/laser/scan, marking: true, clearing: true}

    #point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}