global_costmap:
    global_frame: map
    robot_base_frame: link_chassis
    update_frequency: 10.0
    publish_frequency: 10.0
    resolution: 0.05
    static_map: true
    width: 40.0
    height: 40.0
    rolling_window: false